### ISSUE TITLE
Check Team Project 2 Submission

### ISSUE THREAD

**Issue by antoniob6** [alkerr/JCE-Indoor-Nav#1]
HW2 Submission

**Comment by robi-y** [comment]
Nice work, please add me also to this repository, so I could change issue status.
Some comments:
- Readme: update the project description via repo. settings (it still say "A template repository with wiki for a team project at JCE's software engineering course") 
  - remove or comment out badges that still point to jce-il/template-project
  - Inception: missing diagram (there requirement was not for use case diagram!)
