### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by eranhd** [alkerr/JCE-Indoor-Nav#2]
**הערות**
- [x] הוספה דינאמית של מיקומים
- [x] אין התייחסות של תמיכה במספר שפות
- [x] שמירת השפה שנבחרה אחרי בחירה בlocalstorage
- [x] האב טיפוס הוא רק של UI
      תוסיפו רשימה של מיקומים אפשריים וגם תתחילו לעבוד על האב טיפוס

**Comment by JohnMusleh** [comment]
תיקנו את הכל והוספנו 
PROTOTYPE
בסוף המסמך
