### ISSUE TITLE
Iteration 1 submission

### ISSUE THREAD

**Issue by JohnMusleh** [alkerr/JCE-Indoor-Nav#25]
Presented in front of the class, can you mark it

**Comment by robi-y** [comment]
OK, ASAP..

**Comment by robi-y** [comment]
Some comments:
- Please use the issue template for submitting iterations
- I could not understand from the page wiki (nor the mislestone1 in issues) what are the issues that belong to this iteration!
- no git tag for this iteration
- missing iteration retrospective to the wiki
- no "class materials" section in wiki page, although it is clear that it is not a bad MVP already
